language: dart

sudo: false

branches:
  only:
    - master

jobs:
  include:
    - stage: configlet
      name: 'configlet lint'
      script: ./bin/configlet lint --track-id dart .
      dart: stable

    - stage: unit_test
      name: 'anagram'
      script: ./bin/travis.sh
      env: EXERCISE="anagram"
      dart: stable

    - stage: unit_test
      name: 'armstrong_numbers'
      script: ./bin/travis.sh
      env: EXERCISE="armstrong-numbers"
      dart: stable

stages:
  - configlet
  - unit_test

cache:
  directories:
    - $HOME/.pub-cache
