language: dart

sudo: false

branches:
  only:
    - master

jobs:
  include:
    - stage: Repo
      name: 'configlet lint'
      script:
        - ./bin/fetch-configlet
        - ./bin/configlet version
        - ./bin/configlet lint --track-id dart .
      language: bash

    - stage: Exercises
      name: 'format, analyze and test'
      script: ./bin/travis.sh
      dart:
        - stable
        - dev
        - '1.24.3'
      install: true

stages:
  - Repo
  - Exercises

cache:
  directories:
    - $HOME/.pub-cache
