language: dart

sudo: false

branches:
  only:
    - master

jobs:
  include:
    - stage: Repo
      name: 'configlet lint'
      script:
        - ./bin/fetch-configlet
        - ./bin/configlet version
        - ./bin/configlet lint --track-id dart .
      language: bash

    - stage: Exercises
      name: 'anagram'
      script: ./bin/travis.sh
      env: EXERCISE_DIR="anagram"
      dart: stable
      install: true

    - stage: Exercises
      name: 'armstrong_numbers'
      script: ./bin/travis.sh
      env: EXERCISE_DIR="armstrong-numbers"
      dart: stable
      install: true

stages:
  - Repo
  - Exercises

cache:
  directories:
    - $HOME/.pub-cache
